import os

ANGEL_API_KEY = os.getenv("ANGEL_API_KEY")
ANGEL_CLIENT_ID = os.getenv("ANGEL_CLIENT_ID")
ANGEL_PASSWORD = os.getenv("ANGEL_PASSWORD")
ANGEL_TOTP_SECRET = os.getenv("ANGEL_TOTP_SECRET")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

INDICES = ["NIFTY", "SENSEX"]

FNO_STOCKS = [
    "RELIANCE","HDFCBANK","ICICIBANK","INFY","TCS",
    "HINDUNILVR","SBIN","AXISBANK","LT","BAJFINANCE",
    "BHARTIARTL","KOTAKBANK","HCLTECH","ITC","MARUTI",
    "SUNPHARMA","ULTRACEMCO","WIPRO","ONGC","TECHM",
    "HDFCLIFE","ADANIENT","TITAN","ASIANPAINT","JSWSTEEL",
    "NTPC","POWERGRID","GRASIM","NESTLEIND","M&M",
    "INDUSINDBK","CIPLA","DIVISLAB","TATACONSUM","UPL",
    "DRREDDY","EICHERMOT","BRITANNIA","COALINDIA","SBILIFE",
    "HINDALCO","ADANIPORTS","BAJAJFINSV","HEROMOTOCO","BPCL",
    "SHREECEM","TATAMOTORS","BAJAJ-AUTO","VEDL","ICICIPRULI"
]
